// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/log_service.proto

package log_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsRequest) Reset() {
	*x = QueryLogsRequest{}
	mi := &file_protos_log_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsRequest) ProtoMessage() {}

func (x *QueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_log_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_protos_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryLogsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type QueryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResponse) Reset() {
	*x = QueryLogsResponse{}
	mi := &file_protos_log_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResponse) ProtoMessage() {}

func (x *QueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_log_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_protos_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_protos_log_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_log_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_log_service_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_protos_log_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_log_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_protos_log_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_log_service_proto protoreflect.FileDescriptor

const file_protos_log_service_proto_rawDesc = "" +
	"\n" +
	"\x18protos/log_service.proto\x12\vlog_service\"B\n" +
	"\x10QueryLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"'\n" +
	"\x11QueryLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9b\x01\n" +
	"\n" +
	"LogService\x12J\n" +
	"\tQueryLogs\x12\x1d.log_service.QueryLogsRequest\x1a\x1e.log_service.QueryLogsResponse\x12A\n" +
	"\x06Health\x12\x1a.log_service.HealthRequest\x1a\x1b.log_service.HealthResponseB%Z#proto/log_service_pb;log_service_pbb\x06proto3"

var (
	file_protos_log_service_proto_rawDescOnce sync.Once
	file_protos_log_service_proto_rawDescData []byte
)

func file_protos_log_service_proto_rawDescGZIP() []byte {
	file_protos_log_service_proto_rawDescOnce.Do(func() {
		file_protos_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_log_service_proto_rawDesc), len(file_protos_log_service_proto_rawDesc)))
	})
	return file_protos_log_service_proto_rawDescData
}

var file_protos_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_log_service_proto_goTypes = []any{
	(*QueryLogsRequest)(nil),  // 0: log_service.QueryLogsRequest
	(*QueryLogsResponse)(nil), // 1: log_service.QueryLogsResponse
	(*HealthRequest)(nil),     // 2: log_service.HealthRequest
	(*HealthResponse)(nil),    // 3: log_service.HealthResponse
}
var file_protos_log_service_proto_depIdxs = []int32{
	0, // 0: log_service.LogService.QueryLogs:input_type -> log_service.QueryLogsRequest
	2, // 1: log_service.LogService.Health:input_type -> log_service.HealthRequest
	1, // 2: log_service.LogService.QueryLogs:output_type -> log_service.QueryLogsResponse
	3, // 3: log_service.LogService.Health:output_type -> log_service.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_log_service_proto_init() }
func file_protos_log_service_proto_init() {
	if File_protos_log_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_log_service_proto_rawDesc), len(file_protos_log_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_log_service_proto_goTypes,
		DependencyIndexes: file_protos_log_service_proto_depIdxs,
		MessageInfos:      file_protos_log_service_proto_msgTypes,
	}.Build()
	File_protos_log_service_proto = out.File
	file_protos_log_service_proto_goTypes = nil
	file_protos_log_service_proto_depIdxs = nil
}
