// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: events.proto

package events_pb

import (
	models_pb "apps-hosting.com/messaging/proto/models_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamName int32

const (
	StreamName_APP_STREAM    StreamName = 0
	StreamName_BUILD_STREAM  StreamName = 1
	StreamName_DEPLOY_STREAM StreamName = 2
)

// Enum value maps for StreamName.
var (
	StreamName_name = map[int32]string{
		0: "APP_STREAM",
		1: "BUILD_STREAM",
		2: "DEPLOY_STREAM",
	}
	StreamName_value = map[string]int32{
		"APP_STREAM":    0,
		"BUILD_STREAM":  1,
		"DEPLOY_STREAM": 2,
	}
)

func (x StreamName) Enum() *StreamName {
	p := new(StreamName)
	*p = x
	return p
}

func (x StreamName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamName) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (StreamName) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x StreamName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamName.Descriptor instead.
func (StreamName) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type EventName int32

const (
	EventName_APP_CREATED      EventName = 0
	EventName_APP_DELETED      EventName = 1
	EventName_BUILD_COMPLETED  EventName = 2
	EventName_BUILD_FAILED     EventName = 3
	EventName_DEPLOY_COMPLETED EventName = 4
	EventName_DEPLOY_FAILED    EventName = 5
)

// Enum value maps for EventName.
var (
	EventName_name = map[int32]string{
		0: "APP_CREATED",
		1: "APP_DELETED",
		2: "BUILD_COMPLETED",
		3: "BUILD_FAILED",
		4: "DEPLOY_COMPLETED",
		5: "DEPLOY_FAILED",
	}
	EventName_value = map[string]int32{
		"APP_CREATED":      0,
		"APP_DELETED":      1,
		"BUILD_COMPLETED":  2,
		"BUILD_FAILED":     3,
		"DEPLOY_COMPLETED": 4,
		"DEPLOY_FAILED":    5,
	}
)

func (x EventName) Enum() *EventName {
	p := new(EventName)
	*p = x
	return p
}

func (x EventName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventName) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (EventName) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x EventName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventName.Descriptor instead.
func (EventName) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type AppCreatedEventData struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	UserId              string                         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	App                 *models_pb.App                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	EnvironmentVariable *models_pb.EnvironmentVariable `protobuf:"bytes,3,opt,name=environment_variable,json=environmentVariable,proto3,oneof" json:"environment_variable,omitempty"`
	GitRepository       *models_pb.GitRepository       `protobuf:"bytes,4,opt,name=git_repository,json=gitRepository,proto3" json:"git_repository,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppCreatedEventData) Reset() {
	*x = AppCreatedEventData{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCreatedEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCreatedEventData) ProtoMessage() {}

func (x *AppCreatedEventData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCreatedEventData.ProtoReflect.Descriptor instead.
func (*AppCreatedEventData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *AppCreatedEventData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppCreatedEventData) GetApp() *models_pb.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *AppCreatedEventData) GetEnvironmentVariable() *models_pb.EnvironmentVariable {
	if x != nil {
		return x.EnvironmentVariable
	}
	return nil
}

func (x *AppCreatedEventData) GetGitRepository() *models_pb.GitRepository {
	if x != nil {
		return x.GitRepository
	}
	return nil
}

type AppDeletedEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppDeletedEventData) Reset() {
	*x = AppDeletedEventData{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppDeletedEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeletedEventData) ProtoMessage() {}

func (x *AppDeletedEventData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeletedEventData.ProtoReflect.Descriptor instead.
func (*AppDeletedEventData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *AppDeletedEventData) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppDeletedEventData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type BuildCompletedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	DomainName    string                 `protobuf:"bytes,5,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCompletedData) Reset() {
	*x = BuildCompletedData{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCompletedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCompletedData) ProtoMessage() {}

func (x *BuildCompletedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCompletedData.ProtoReflect.Descriptor instead.
func (*BuildCompletedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *BuildCompletedData) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BuildCompletedData) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildCompletedData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *BuildCompletedData) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BuildCompletedData) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type BuildFailedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFailedData) Reset() {
	*x = BuildFailedData{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFailedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFailedData) ProtoMessage() {}

func (x *BuildFailedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFailedData.ProtoReflect.Descriptor instead.
func (*BuildFailedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *BuildFailedData) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BuildFailedData) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildFailedData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *BuildFailedData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeployCompletedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeployId      string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployCompletedData) Reset() {
	*x = DeployCompletedData{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployCompletedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCompletedData) ProtoMessage() {}

func (x *DeployCompletedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCompletedData.ProtoReflect.Descriptor instead.
func (*DeployCompletedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *DeployCompletedData) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *DeployCompletedData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type DeployFailedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployFailedData) Reset() {
	*x = DeployFailedData{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployFailedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployFailedData) ProtoMessage() {}

func (x *DeployFailedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployFailedData.ProtoReflect.Descriptor instead.
func (*DeployFailedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *DeployFailedData) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeployFailedData) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *DeployFailedData) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployFailedData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DeployFailedData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*EventData_AppCreatedData
	//	*EventData_AppDeletedData
	//	*EventData_BuildCompletedData
	//	*EventData_BuildFailedData
	//	*EventData_DeployCompletedData
	//	*EventData_DeployFailedData
	Value         isEventData_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventData) GetValue() isEventData_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EventData) GetAppCreatedData() *AppCreatedEventData {
	if x != nil {
		if x, ok := x.Value.(*EventData_AppCreatedData); ok {
			return x.AppCreatedData
		}
	}
	return nil
}

func (x *EventData) GetAppDeletedData() *AppDeletedEventData {
	if x != nil {
		if x, ok := x.Value.(*EventData_AppDeletedData); ok {
			return x.AppDeletedData
		}
	}
	return nil
}

func (x *EventData) GetBuildCompletedData() *BuildCompletedData {
	if x != nil {
		if x, ok := x.Value.(*EventData_BuildCompletedData); ok {
			return x.BuildCompletedData
		}
	}
	return nil
}

func (x *EventData) GetBuildFailedData() *BuildFailedData {
	if x != nil {
		if x, ok := x.Value.(*EventData_BuildFailedData); ok {
			return x.BuildFailedData
		}
	}
	return nil
}

func (x *EventData) GetDeployCompletedData() *DeployCompletedData {
	if x != nil {
		if x, ok := x.Value.(*EventData_DeployCompletedData); ok {
			return x.DeployCompletedData
		}
	}
	return nil
}

func (x *EventData) GetDeployFailedData() *DeployFailedData {
	if x != nil {
		if x, ok := x.Value.(*EventData_DeployFailedData); ok {
			return x.DeployFailedData
		}
	}
	return nil
}

type isEventData_Value interface {
	isEventData_Value()
}

type EventData_AppCreatedData struct {
	AppCreatedData *AppCreatedEventData `protobuf:"bytes,1,opt,name=app_created_data,json=appCreatedData,proto3,oneof"`
}

type EventData_AppDeletedData struct {
	AppDeletedData *AppDeletedEventData `protobuf:"bytes,2,opt,name=app_deleted_data,json=appDeletedData,proto3,oneof"`
}

type EventData_BuildCompletedData struct {
	BuildCompletedData *BuildCompletedData `protobuf:"bytes,3,opt,name=build_completed_data,json=buildCompletedData,proto3,oneof"`
}

type EventData_BuildFailedData struct {
	BuildFailedData *BuildFailedData `protobuf:"bytes,4,opt,name=build_failed_data,json=buildFailedData,proto3,oneof"`
}

type EventData_DeployCompletedData struct {
	DeployCompletedData *DeployCompletedData `protobuf:"bytes,5,opt,name=deploy_completed_data,json=deployCompletedData,proto3,oneof"`
}

type EventData_DeployFailedData struct {
	DeployFailedData *DeployFailedData `protobuf:"bytes,6,opt,name=deploy_failed_data,json=deployFailedData,proto3,oneof"`
}

func (*EventData_AppCreatedData) isEventData_Value() {}

func (*EventData_AppDeletedData) isEventData_Value() {}

func (*EventData_BuildCompletedData) isEventData_Value() {}

func (*EventData_BuildFailedData) isEventData_Value() {}

func (*EventData_DeployCompletedData) isEventData_Value() {}

func (*EventData_DeployFailedData) isEventData_Value() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventName     EventName              `protobuf:"varint,2,opt,name=event_name,json=eventName,proto3,enum=events.EventName" json:"event_name,omitempty"`
	Data          *EventData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetEventName() EventName {
	if x != nil {
		return x.EventName
	}
	return EventName_APP_CREATED
}

func (x *Message) GetData() *EventData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x06events\x1a\fmodels.proto\"\xf9\x01\n" +
	"\x13AppCreatedEventData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\x03app\x18\x02 \x01(\v2\v.models.AppR\x03app\x12S\n" +
	"\x14environment_variable\x18\x03 \x01(\v2\x1b.models.EnvironmentVariableH\x00R\x13environmentVariable\x88\x01\x01\x12<\n" +
	"\x0egit_repository\x18\x04 \x01(\v2\x15.models.GitRepositoryR\rgitRepositoryB\x17\n" +
	"\x15_environment_variable\"G\n" +
	"\x13AppDeletedEventData\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"\x9f\x01\n" +
	"\x12BuildCompletedData\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vdomain_name\x18\x05 \x01(\tR\n" +
	"domainName\"v\n" +
	"\x0fBuildFailedData\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"M\n" +
	"\x13DeployCompletedData\x12\x1b\n" +
	"\tdeploy_id\x18\x01 \x01(\tR\bdeployId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"\x9c\x01\n" +
	"\x10DeployFailedData\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xda\x03\n" +
	"\tEventData\x12G\n" +
	"\x10app_created_data\x18\x01 \x01(\v2\x1b.events.AppCreatedEventDataH\x00R\x0eappCreatedData\x12G\n" +
	"\x10app_deleted_data\x18\x02 \x01(\v2\x1b.events.AppDeletedEventDataH\x00R\x0eappDeletedData\x12N\n" +
	"\x14build_completed_data\x18\x03 \x01(\v2\x1a.events.BuildCompletedDataH\x00R\x12buildCompletedData\x12E\n" +
	"\x11build_failed_data\x18\x04 \x01(\v2\x17.events.BuildFailedDataH\x00R\x0fbuildFailedData\x12Q\n" +
	"\x15deploy_completed_data\x18\x05 \x01(\v2\x1b.events.DeployCompletedDataH\x00R\x13deployCompletedData\x12H\n" +
	"\x12deploy_failed_data\x18\x06 \x01(\v2\x18.events.DeployFailedDataH\x00R\x10deployFailedDataB\a\n" +
	"\x05value\"\x90\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\n" +
	"event_name\x18\x02 \x01(\x0e2\x11.events.EventNameR\teventName\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.events.EventDataR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*A\n" +
	"\n" +
	"StreamName\x12\x0e\n" +
	"\n" +
	"APP_STREAM\x10\x00\x12\x10\n" +
	"\fBUILD_STREAM\x10\x01\x12\x11\n" +
	"\rDEPLOY_STREAM\x10\x02*}\n" +
	"\tEventName\x12\x0f\n" +
	"\vAPP_CREATED\x10\x00\x12\x0f\n" +
	"\vAPP_DELETED\x10\x01\x12\x13\n" +
	"\x0fBUILD_COMPLETED\x10\x02\x12\x10\n" +
	"\fBUILD_FAILED\x10\x03\x12\x14\n" +
	"\x10DEPLOY_COMPLETED\x10\x04\x12\x11\n" +
	"\rDEPLOY_FAILED\x10\x05B\x1bZ\x19proto/events_pb;events_pbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_events_proto_goTypes = []any{
	(StreamName)(0),                       // 0: events.StreamName
	(EventName)(0),                        // 1: events.EventName
	(*AppCreatedEventData)(nil),           // 2: events.AppCreatedEventData
	(*AppDeletedEventData)(nil),           // 3: events.AppDeletedEventData
	(*BuildCompletedData)(nil),            // 4: events.BuildCompletedData
	(*BuildFailedData)(nil),               // 5: events.BuildFailedData
	(*DeployCompletedData)(nil),           // 6: events.DeployCompletedData
	(*DeployFailedData)(nil),              // 7: events.DeployFailedData
	(*EventData)(nil),                     // 8: events.EventData
	(*Message)(nil),                       // 9: events.Message
	(*models_pb.App)(nil),                 // 10: models.App
	(*models_pb.EnvironmentVariable)(nil), // 11: models.EnvironmentVariable
	(*models_pb.GitRepository)(nil),       // 12: models.GitRepository
}
var file_events_proto_depIdxs = []int32{
	10, // 0: events.AppCreatedEventData.app:type_name -> models.App
	11, // 1: events.AppCreatedEventData.environment_variable:type_name -> models.EnvironmentVariable
	12, // 2: events.AppCreatedEventData.git_repository:type_name -> models.GitRepository
	2,  // 3: events.EventData.app_created_data:type_name -> events.AppCreatedEventData
	3,  // 4: events.EventData.app_deleted_data:type_name -> events.AppDeletedEventData
	4,  // 5: events.EventData.build_completed_data:type_name -> events.BuildCompletedData
	5,  // 6: events.EventData.build_failed_data:type_name -> events.BuildFailedData
	6,  // 7: events.EventData.deploy_completed_data:type_name -> events.DeployCompletedData
	7,  // 8: events.EventData.deploy_failed_data:type_name -> events.DeployFailedData
	1,  // 9: events.Message.event_name:type_name -> events.EventName
	8,  // 10: events.Message.data:type_name -> events.EventData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_events_proto_msgTypes[6].OneofWrappers = []any{
		(*EventData_AppCreatedData)(nil),
		(*EventData_AppDeletedData)(nil),
		(*EventData_BuildCompletedData)(nil),
		(*EventData_BuildFailedData)(nil),
		(*EventData_DeployCompletedData)(nil),
		(*EventData_DeployFailedData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
