// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: src/protos/app_service.proto

package app_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DomainName    string                 `protobuf:"bytes,4,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	Runtime       string                 `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,6,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	BuildCmd      string                 `protobuf:"bytes,7,opt,name=build_cmd,json=buildCmd,proto3" json:"build_cmd,omitempty"`
	StartCmd      string                 `protobuf:"bytes,8,opt,name=start_cmd,json=startCmd,proto3" json:"start_cmd,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_src_protos_app_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *App) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *App) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *App) GetBuildCmd() string {
	if x != nil {
		return x.BuildCmd
	}
	return ""
}

func (x *App) GetStartCmd() string {
	if x != nil {
		return x.StartCmd
	}
	return ""
}

func (x *App) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type EnvironmentVariables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreateAt      string                 `protobuf:"bytes,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentVariables) Reset() {
	*x = EnvironmentVariables{}
	mi := &file_src_protos_app_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentVariables) ProtoMessage() {}

func (x *EnvironmentVariables) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentVariables.ProtoReflect.Descriptor instead.
func (*EnvironmentVariables) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentVariables) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvironmentVariables) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvironmentVariables) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type GitRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,4,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRepository) Reset() {
	*x = GitRepository{}
	mi := &file_src_protos_app_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepository) ProtoMessage() {}

func (x *GitRepository) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRepository.ProtoReflect.Descriptor instead.
func (*GitRepository) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{2}
}

func (x *GitRepository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitRepository) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GitRepository) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GitRepository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *GitRepository) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GitRepository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAppRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProjectId            string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Runtime              string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	GitRepository        *GitRepository         `protobuf:"bytes,5,opt,name=git_repository,json=gitRepository,proto3" json:"git_repository,omitempty"`
	BuildCmd             string                 `protobuf:"bytes,6,opt,name=build_cmd,json=buildCmd,proto3" json:"build_cmd,omitempty"`
	StartCmd             string                 `protobuf:"bytes,7,opt,name=start_cmd,json=startCmd,proto3" json:"start_cmd,omitempty"`
	EnvironmentVariables *string                `protobuf:"bytes,8,opt,name=environment_variables,json=environmentVariables,proto3,oneof" json:"environment_variables,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAppRequest) Reset() {
	*x = CreateAppRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppRequest) ProtoMessage() {}

func (x *CreateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppRequest.ProtoReflect.Descriptor instead.
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAppRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateAppRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAppRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *CreateAppRequest) GetGitRepository() *GitRepository {
	if x != nil {
		return x.GitRepository
	}
	return nil
}

func (x *CreateAppRequest) GetBuildCmd() string {
	if x != nil {
		return x.BuildCmd
	}
	return ""
}

func (x *CreateAppRequest) GetStartCmd() string {
	if x != nil {
		return x.StartCmd
	}
	return ""
}

func (x *CreateAppRequest) GetEnvironmentVariables() string {
	if x != nil && x.EnvironmentVariables != nil {
		return *x.EnvironmentVariables
	}
	return ""
}

type CreateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppResponse) Reset() {
	*x = CreateAppResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppResponse) ProtoMessage() {}

func (x *CreateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppResponse.ProtoReflect.Descriptor instead.
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type GetAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppRequest) Reset() {
	*x = GetAppRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppRequest) ProtoMessage() {}

func (x *GetAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppRequest.ProtoReflect.Descriptor instead.
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAppRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppResponse) Reset() {
	*x = GetAppResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppResponse) ProtoMessage() {}

func (x *GetAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppResponse.ProtoReflect.Descriptor instead.
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type GetAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsRequest) Reset() {
	*x = GetAppsRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsRequest) ProtoMessage() {}

func (x *GetAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsRequest.ProtoReflect.Descriptor instead.
func (*GetAppsRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*App                 `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsResponse) Reset() {
	*x = GetAppsResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsResponse) ProtoMessage() {}

func (x *GetAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsResponse.ProtoReflect.Descriptor instead.
func (*GetAppsResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAppsResponse) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type UpdateAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BuildCmd      *string                `protobuf:"bytes,4,opt,name=build_cmd,json=buildCmd,proto3,oneof" json:"build_cmd,omitempty"`
	StartCmd      *string                `protobuf:"bytes,5,opt,name=start_cmd,json=startCmd,proto3,oneof" json:"start_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppRequest) Reset() {
	*x = UpdateAppRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppRequest) ProtoMessage() {}

func (x *UpdateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAppRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateAppRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAppRequest) GetBuildCmd() string {
	if x != nil && x.BuildCmd != nil {
		return *x.BuildCmd
	}
	return ""
}

func (x *UpdateAppRequest) GetStartCmd() string {
	if x != nil && x.StartCmd != nil {
		return *x.StartCmd
	}
	return ""
}

type UpdateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppResponse) Reset() {
	*x = UpdateAppResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppResponse) ProtoMessage() {}

func (x *UpdateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type DeleteAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAppRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DeleteAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppResponse) Reset() {
	*x = DeleteAppResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResponse) ProtoMessage() {}

func (x *DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{12}
}

type GetEnvironmentVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentVariablesRequest) Reset() {
	*x = GetEnvironmentVariablesRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentVariablesRequest) ProtoMessage() {}

func (x *GetEnvironmentVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentVariablesRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentVariablesRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetEnvironmentVariablesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetEnvironmentVariablesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentVariable *EnvironmentVariables  `protobuf:"bytes,1,opt,name=environment_variable,json=environmentVariable,proto3" json:"environment_variable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEnvironmentVariablesResponse) Reset() {
	*x = GetEnvironmentVariablesResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentVariablesResponse) ProtoMessage() {}

func (x *GetEnvironmentVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentVariablesResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentVariablesResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetEnvironmentVariablesResponse) GetEnvironmentVariable() *EnvironmentVariables {
	if x != nil {
		return x.EnvironmentVariable
	}
	return nil
}

type CreateEnvironmentVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentVariablesRequest) Reset() {
	*x = CreateEnvironmentVariablesRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentVariablesRequest) ProtoMessage() {}

func (x *CreateEnvironmentVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentVariablesRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentVariablesRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateEnvironmentVariablesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateEnvironmentVariablesRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateEnvironmentVariablesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentVariable *EnvironmentVariables  `protobuf:"bytes,1,opt,name=environment_variable,json=environmentVariable,proto3" json:"environment_variable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateEnvironmentVariablesResponse) Reset() {
	*x = CreateEnvironmentVariablesResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentVariablesResponse) ProtoMessage() {}

func (x *CreateEnvironmentVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentVariablesResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentVariablesResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateEnvironmentVariablesResponse) GetEnvironmentVariable() *EnvironmentVariables {
	if x != nil {
		return x.EnvironmentVariable
	}
	return nil
}

type UpdateEnvironmentVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvironmentVariablesRequest) Reset() {
	*x = UpdateEnvironmentVariablesRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentVariablesRequest) ProtoMessage() {}

func (x *UpdateEnvironmentVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentVariablesRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentVariablesRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateEnvironmentVariablesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateEnvironmentVariablesRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateEnvironmentVariablesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentVariable *EnvironmentVariables  `protobuf:"bytes,1,opt,name=environment_variable,json=environmentVariable,proto3" json:"environment_variable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateEnvironmentVariablesResponse) Reset() {
	*x = UpdateEnvironmentVariablesResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentVariablesResponse) ProtoMessage() {}

func (x *UpdateEnvironmentVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentVariablesResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentVariablesResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEnvironmentVariablesResponse) GetEnvironmentVariable() *EnvironmentVariables {
	if x != nil {
		return x.EnvironmentVariable
	}
	return nil
}

type DeleteEnvironmentVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentVariablesRequest) Reset() {
	*x = DeleteEnvironmentVariablesRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentVariablesRequest) ProtoMessage() {}

func (x *DeleteEnvironmentVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentVariablesRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentVariablesRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteEnvironmentVariablesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DeleteEnvironmentVariablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentVariablesResponse) Reset() {
	*x = DeleteEnvironmentVariablesResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentVariablesResponse) ProtoMessage() {}

func (x *DeleteEnvironmentVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentVariablesResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentVariablesResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{20}
}

type BatchGetAppsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectIds    []string               `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetAppsCountRequest) Reset() {
	*x = BatchGetAppsCountRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAppsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAppsCountRequest) ProtoMessage() {}

func (x *BatchGetAppsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAppsCountRequest.ProtoReflect.Descriptor instead.
func (*BatchGetAppsCountRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{21}
}

func (x *BatchGetAppsCountRequest) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

type BatchGetAppsCountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectAppsCount map[string]int32       `protobuf:"bytes,1,rep,name=project_apps_count,json=projectAppsCount,proto3" json:"project_apps_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchGetAppsCountResponse) Reset() {
	*x = BatchGetAppsCountResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAppsCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAppsCountResponse) ProtoMessage() {}

func (x *BatchGetAppsCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAppsCountResponse.ProtoReflect.Descriptor instead.
func (*BatchGetAppsCountResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{22}
}

func (x *BatchGetAppsCountResponse) GetProjectAppsCount() map[string]int32 {
	if x != nil {
		return x.ProjectAppsCount
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_src_protos_app_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{23}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_src_protos_app_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_app_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_app_service_proto_rawDescGZIP(), []int{24}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_protos_app_service_proto protoreflect.FileDescriptor

const file_src_protos_app_service_proto_rawDesc = "" +
	"\n" +
	"\x1csrc/protos/app_service.proto\x12\vapp_service\"\xf7\x01\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vdomain_name\x18\x04 \x01(\tR\n" +
	"domainName\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\x12\x19\n" +
	"\brepo_url\x18\x06 \x01(\tR\arepoUrl\x12\x1b\n" +
	"\tbuild_cmd\x18\a \x01(\tR\bbuildCmd\x12\x1b\n" +
	"\tstart_cmd\x18\b \x01(\tR\bstartCmd\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"Y\n" +
	"\x14EnvironmentVariables\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tcreate_at\x18\x03 \x01(\tR\bcreateAt\"\xad\x01\n" +
	"\rGitRepository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tclone_url\x18\x04 \x01(\tR\bcloneUrl\x12\x1d\n" +
	"\n" +
	"is_private\x18\x05 \x01(\bR\tisPrivate\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xc9\x02\n" +
	"\x10CreateAppRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12A\n" +
	"\x0egit_repository\x18\x05 \x01(\v2\x1a.app_service.GitRepositoryR\rgitRepository\x12\x1b\n" +
	"\tbuild_cmd\x18\x06 \x01(\tR\bbuildCmd\x12\x1b\n" +
	"\tstart_cmd\x18\a \x01(\tR\bstartCmd\x128\n" +
	"\x15environment_variables\x18\b \x01(\tH\x00R\x14environmentVariables\x88\x01\x01B\x18\n" +
	"\x16_environment_variables\"7\n" +
	"\x11CreateAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.app_service.AppR\x03app\"E\n" +
	"\rGetAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"4\n" +
	"\x0eGetAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.app_service.AppR\x03app\"/\n" +
	"\x0eGetAppsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"7\n" +
	"\x0fGetAppsResponse\x12$\n" +
	"\x04apps\x18\x01 \x03(\v2\x10.app_service.AppR\x04apps\"\xca\x01\n" +
	"\x10UpdateAppRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tbuild_cmd\x18\x04 \x01(\tH\x01R\bbuildCmd\x88\x01\x01\x12 \n" +
	"\tstart_cmd\x18\x05 \x01(\tH\x02R\bstartCmd\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_build_cmdB\f\n" +
	"\n" +
	"_start_cmd\"7\n" +
	"\x11UpdateAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.app_service.AppR\x03app\"H\n" +
	"\x10DeleteAppRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"\x13\n" +
	"\x11DeleteAppResponse\"7\n" +
	"\x1eGetEnvironmentVariablesRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"w\n" +
	"\x1fGetEnvironmentVariablesResponse\x12T\n" +
	"\x14environment_variable\x18\x01 \x01(\v2!.app_service.EnvironmentVariablesR\x13environmentVariable\"P\n" +
	"!CreateEnvironmentVariablesRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"z\n" +
	"\"CreateEnvironmentVariablesResponse\x12T\n" +
	"\x14environment_variable\x18\x01 \x01(\v2!.app_service.EnvironmentVariablesR\x13environmentVariable\"P\n" +
	"!UpdateEnvironmentVariablesRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"z\n" +
	"\"UpdateEnvironmentVariablesResponse\x12T\n" +
	"\x14environment_variable\x18\x01 \x01(\v2!.app_service.EnvironmentVariablesR\x13environmentVariable\":\n" +
	"!DeleteEnvironmentVariablesRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"$\n" +
	"\"DeleteEnvironmentVariablesResponse\";\n" +
	"\x18BatchGetAppsCountRequest\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\"\xcc\x01\n" +
	"\x19BatchGetAppsCountResponse\x12j\n" +
	"\x12project_apps_count\x18\x01 \x03(\v2<.app_service.BatchGetAppsCountResponse.ProjectAppsCountEntryR\x10projectAppsCount\x1aC\n" +
	"\x15ProjectAppsCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x93\b\n" +
	"\n" +
	"AppService\x12A\n" +
	"\x06Health\x12\x1a.app_service.HealthRequest\x1a\x1b.app_service.HealthResponse\x12J\n" +
	"\tCreateApp\x12\x1d.app_service.CreateAppRequest\x1a\x1e.app_service.CreateAppResponse\x12A\n" +
	"\x06GetApp\x12\x1a.app_service.GetAppRequest\x1a\x1b.app_service.GetAppResponse\x12D\n" +
	"\aGetApps\x12\x1b.app_service.GetAppsRequest\x1a\x1c.app_service.GetAppsResponse\x12J\n" +
	"\tUpdateApp\x12\x1d.app_service.UpdateAppRequest\x1a\x1e.app_service.UpdateAppResponse\x12J\n" +
	"\tDeleteApp\x12\x1d.app_service.DeleteAppRequest\x1a\x1e.app_service.DeleteAppResponse\x12t\n" +
	"\x17GetEnvironmentVariables\x12+.app_service.GetEnvironmentVariablesRequest\x1a,.app_service.GetEnvironmentVariablesResponse\x12}\n" +
	"\x1aCreateEnvironmentVariables\x12..app_service.CreateEnvironmentVariablesRequest\x1a/.app_service.CreateEnvironmentVariablesResponse\x12}\n" +
	"\x1aUpdateEnvironmentVariables\x12..app_service.UpdateEnvironmentVariablesRequest\x1a/.app_service.UpdateEnvironmentVariablesResponse\x12}\n" +
	"\x1aDeleteEnvironmentVariables\x12..app_service.DeleteEnvironmentVariablesRequest\x1a/.app_service.DeleteEnvironmentVariablesResponse\x12b\n" +
	"\x11BatchGetAppsCount\x12%.app_service.BatchGetAppsCountRequest\x1a&.app_service.BatchGetAppsCountResponseB%Z#proto/app_service_pb;app_service_pbb\x06proto3"

var (
	file_src_protos_app_service_proto_rawDescOnce sync.Once
	file_src_protos_app_service_proto_rawDescData []byte
)

func file_src_protos_app_service_proto_rawDescGZIP() []byte {
	file_src_protos_app_service_proto_rawDescOnce.Do(func() {
		file_src_protos_app_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_app_service_proto_rawDesc), len(file_src_protos_app_service_proto_rawDesc)))
	})
	return file_src_protos_app_service_proto_rawDescData
}

var file_src_protos_app_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_src_protos_app_service_proto_goTypes = []any{
	(*App)(nil),                                // 0: app_service.App
	(*EnvironmentVariables)(nil),               // 1: app_service.EnvironmentVariables
	(*GitRepository)(nil),                      // 2: app_service.GitRepository
	(*CreateAppRequest)(nil),                   // 3: app_service.CreateAppRequest
	(*CreateAppResponse)(nil),                  // 4: app_service.CreateAppResponse
	(*GetAppRequest)(nil),                      // 5: app_service.GetAppRequest
	(*GetAppResponse)(nil),                     // 6: app_service.GetAppResponse
	(*GetAppsRequest)(nil),                     // 7: app_service.GetAppsRequest
	(*GetAppsResponse)(nil),                    // 8: app_service.GetAppsResponse
	(*UpdateAppRequest)(nil),                   // 9: app_service.UpdateAppRequest
	(*UpdateAppResponse)(nil),                  // 10: app_service.UpdateAppResponse
	(*DeleteAppRequest)(nil),                   // 11: app_service.DeleteAppRequest
	(*DeleteAppResponse)(nil),                  // 12: app_service.DeleteAppResponse
	(*GetEnvironmentVariablesRequest)(nil),     // 13: app_service.GetEnvironmentVariablesRequest
	(*GetEnvironmentVariablesResponse)(nil),    // 14: app_service.GetEnvironmentVariablesResponse
	(*CreateEnvironmentVariablesRequest)(nil),  // 15: app_service.CreateEnvironmentVariablesRequest
	(*CreateEnvironmentVariablesResponse)(nil), // 16: app_service.CreateEnvironmentVariablesResponse
	(*UpdateEnvironmentVariablesRequest)(nil),  // 17: app_service.UpdateEnvironmentVariablesRequest
	(*UpdateEnvironmentVariablesResponse)(nil), // 18: app_service.UpdateEnvironmentVariablesResponse
	(*DeleteEnvironmentVariablesRequest)(nil),  // 19: app_service.DeleteEnvironmentVariablesRequest
	(*DeleteEnvironmentVariablesResponse)(nil), // 20: app_service.DeleteEnvironmentVariablesResponse
	(*BatchGetAppsCountRequest)(nil),           // 21: app_service.BatchGetAppsCountRequest
	(*BatchGetAppsCountResponse)(nil),          // 22: app_service.BatchGetAppsCountResponse
	(*HealthRequest)(nil),                      // 23: app_service.HealthRequest
	(*HealthResponse)(nil),                     // 24: app_service.HealthResponse
	nil,                                        // 25: app_service.BatchGetAppsCountResponse.ProjectAppsCountEntry
}
var file_src_protos_app_service_proto_depIdxs = []int32{
	2,  // 0: app_service.CreateAppRequest.git_repository:type_name -> app_service.GitRepository
	0,  // 1: app_service.CreateAppResponse.app:type_name -> app_service.App
	0,  // 2: app_service.GetAppResponse.app:type_name -> app_service.App
	0,  // 3: app_service.GetAppsResponse.apps:type_name -> app_service.App
	0,  // 4: app_service.UpdateAppResponse.app:type_name -> app_service.App
	1,  // 5: app_service.GetEnvironmentVariablesResponse.environment_variable:type_name -> app_service.EnvironmentVariables
	1,  // 6: app_service.CreateEnvironmentVariablesResponse.environment_variable:type_name -> app_service.EnvironmentVariables
	1,  // 7: app_service.UpdateEnvironmentVariablesResponse.environment_variable:type_name -> app_service.EnvironmentVariables
	25, // 8: app_service.BatchGetAppsCountResponse.project_apps_count:type_name -> app_service.BatchGetAppsCountResponse.ProjectAppsCountEntry
	23, // 9: app_service.AppService.Health:input_type -> app_service.HealthRequest
	3,  // 10: app_service.AppService.CreateApp:input_type -> app_service.CreateAppRequest
	5,  // 11: app_service.AppService.GetApp:input_type -> app_service.GetAppRequest
	7,  // 12: app_service.AppService.GetApps:input_type -> app_service.GetAppsRequest
	9,  // 13: app_service.AppService.UpdateApp:input_type -> app_service.UpdateAppRequest
	11, // 14: app_service.AppService.DeleteApp:input_type -> app_service.DeleteAppRequest
	13, // 15: app_service.AppService.GetEnvironmentVariables:input_type -> app_service.GetEnvironmentVariablesRequest
	15, // 16: app_service.AppService.CreateEnvironmentVariables:input_type -> app_service.CreateEnvironmentVariablesRequest
	17, // 17: app_service.AppService.UpdateEnvironmentVariables:input_type -> app_service.UpdateEnvironmentVariablesRequest
	19, // 18: app_service.AppService.DeleteEnvironmentVariables:input_type -> app_service.DeleteEnvironmentVariablesRequest
	21, // 19: app_service.AppService.BatchGetAppsCount:input_type -> app_service.BatchGetAppsCountRequest
	24, // 20: app_service.AppService.Health:output_type -> app_service.HealthResponse
	4,  // 21: app_service.AppService.CreateApp:output_type -> app_service.CreateAppResponse
	6,  // 22: app_service.AppService.GetApp:output_type -> app_service.GetAppResponse
	8,  // 23: app_service.AppService.GetApps:output_type -> app_service.GetAppsResponse
	10, // 24: app_service.AppService.UpdateApp:output_type -> app_service.UpdateAppResponse
	12, // 25: app_service.AppService.DeleteApp:output_type -> app_service.DeleteAppResponse
	14, // 26: app_service.AppService.GetEnvironmentVariables:output_type -> app_service.GetEnvironmentVariablesResponse
	16, // 27: app_service.AppService.CreateEnvironmentVariables:output_type -> app_service.CreateEnvironmentVariablesResponse
	18, // 28: app_service.AppService.UpdateEnvironmentVariables:output_type -> app_service.UpdateEnvironmentVariablesResponse
	20, // 29: app_service.AppService.DeleteEnvironmentVariables:output_type -> app_service.DeleteEnvironmentVariablesResponse
	22, // 30: app_service.AppService.BatchGetAppsCount:output_type -> app_service.BatchGetAppsCountResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_src_protos_app_service_proto_init() }
func file_src_protos_app_service_proto_init() {
	if File_src_protos_app_service_proto != nil {
		return
	}
	file_src_protos_app_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_src_protos_app_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_app_service_proto_rawDesc), len(file_src_protos_app_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_app_service_proto_goTypes,
		DependencyIndexes: file_src_protos_app_service_proto_depIdxs,
		MessageInfos:      file_src_protos_app_service_proto_msgTypes,
	}.Build()
	File_src_protos_app_service_proto = out.File
	file_src_protos_app_service_proto_goTypes = nil
	file_src_protos_app_service_proto_depIdxs = nil
}
