// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: src/protos/project_service.proto

package project_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_src_protos_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_src_protos_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_src_protos_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetUserProjectByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdRequest) Reset() {
	*x = GetUserProjectByIdRequest{}
	mi := &file_src_protos_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdRequest) ProtoMessage() {}

func (x *GetUserProjectByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProjectByIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetUserProjectByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProjectByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdResponse) Reset() {
	*x = GetUserProjectByIdResponse{}
	mi := &file_src_protos_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdResponse) ProtoMessage() {}

func (x *GetUserProjectByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProjectByIdResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetUserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsRequest) Reset() {
	*x = GetUserProjectsRequest{}
	mi := &file_src_protos_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsRequest) ProtoMessage() {}

func (x *GetUserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsResponse) Reset() {
	*x = GetUserProjectsResponse{}
	mi := &file_src_protos_project_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsResponse) ProtoMessage() {}

func (x *GetUserProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectsResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type DeleteUserProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProjectRequest) Reset() {
	*x = DeleteUserProjectRequest{}
	mi := &file_src_protos_project_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProjectRequest) ProtoMessage() {}

func (x *DeleteUserProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserProjectRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteUserProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProjectResponse) Reset() {
	*x = DeleteUserProjectResponse{}
	mi := &file_src_protos_project_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProjectResponse) ProtoMessage() {}

func (x *DeleteUserProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserProjectResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{8}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_src_protos_project_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_src_protos_project_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_project_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_project_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_protos_project_service_proto protoreflect.FileDescriptor

const file_src_protos_project_service_proto_rawDesc = "" +
	"\n" +
	" src/protos/project_service.proto\x12\x0fproject_service\"e\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"C\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"K\n" +
	"\x15CreateProjectResponse\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.project_service.ProjectR\aproject\"S\n" +
	"\x19GetUserProjectByIdRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x1aGetUserProjectByIdResponse\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.project_service.ProjectR\aproject\"1\n" +
	"\x16GetUserProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x17GetUserProjectsResponse\x124\n" +
	"\bprojects\x18\x01 \x03(\v2\x18.project_service.ProjectR\bprojects\"R\n" +
	"\x18DeleteUserProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1b\n" +
	"\x19DeleteUserProjectResponse\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfc\x03\n" +
	"\x0eProjectService\x12I\n" +
	"\x06Health\x12\x1e.project_service.HealthRequest\x1a\x1f.project_service.HealthResponse\x12^\n" +
	"\rCreateProject\x12%.project_service.CreateProjectRequest\x1a&.project_service.CreateProjectResponse\x12m\n" +
	"\x12GetUserProjectById\x12*.project_service.GetUserProjectByIdRequest\x1a+.project_service.GetUserProjectByIdResponse\x12d\n" +
	"\x0fGetUserProjects\x12'.project_service.GetUserProjectsRequest\x1a(.project_service.GetUserProjectsResponse\x12j\n" +
	"\x11DeleteUserProject\x12).project_service.DeleteUserProjectRequest\x1a*.project_service.DeleteUserProjectResponseB-Z+proto/project_service_pb;project_service_pbb\x06proto3"

var (
	file_src_protos_project_service_proto_rawDescOnce sync.Once
	file_src_protos_project_service_proto_rawDescData []byte
)

func file_src_protos_project_service_proto_rawDescGZIP() []byte {
	file_src_protos_project_service_proto_rawDescOnce.Do(func() {
		file_src_protos_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_project_service_proto_rawDesc), len(file_src_protos_project_service_proto_rawDesc)))
	})
	return file_src_protos_project_service_proto_rawDescData
}

var file_src_protos_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_src_protos_project_service_proto_goTypes = []any{
	(*Project)(nil),                    // 0: project_service.Project
	(*CreateProjectRequest)(nil),       // 1: project_service.CreateProjectRequest
	(*CreateProjectResponse)(nil),      // 2: project_service.CreateProjectResponse
	(*GetUserProjectByIdRequest)(nil),  // 3: project_service.GetUserProjectByIdRequest
	(*GetUserProjectByIdResponse)(nil), // 4: project_service.GetUserProjectByIdResponse
	(*GetUserProjectsRequest)(nil),     // 5: project_service.GetUserProjectsRequest
	(*GetUserProjectsResponse)(nil),    // 6: project_service.GetUserProjectsResponse
	(*DeleteUserProjectRequest)(nil),   // 7: project_service.DeleteUserProjectRequest
	(*DeleteUserProjectResponse)(nil),  // 8: project_service.DeleteUserProjectResponse
	(*HealthRequest)(nil),              // 9: project_service.HealthRequest
	(*HealthResponse)(nil),             // 10: project_service.HealthResponse
}
var file_src_protos_project_service_proto_depIdxs = []int32{
	0,  // 0: project_service.CreateProjectResponse.project:type_name -> project_service.Project
	0,  // 1: project_service.GetUserProjectByIdResponse.project:type_name -> project_service.Project
	0,  // 2: project_service.GetUserProjectsResponse.projects:type_name -> project_service.Project
	9,  // 3: project_service.ProjectService.Health:input_type -> project_service.HealthRequest
	1,  // 4: project_service.ProjectService.CreateProject:input_type -> project_service.CreateProjectRequest
	3,  // 5: project_service.ProjectService.GetUserProjectById:input_type -> project_service.GetUserProjectByIdRequest
	5,  // 6: project_service.ProjectService.GetUserProjects:input_type -> project_service.GetUserProjectsRequest
	7,  // 7: project_service.ProjectService.DeleteUserProject:input_type -> project_service.DeleteUserProjectRequest
	10, // 8: project_service.ProjectService.Health:output_type -> project_service.HealthResponse
	2,  // 9: project_service.ProjectService.CreateProject:output_type -> project_service.CreateProjectResponse
	4,  // 10: project_service.ProjectService.GetUserProjectById:output_type -> project_service.GetUserProjectByIdResponse
	6,  // 11: project_service.ProjectService.GetUserProjects:output_type -> project_service.GetUserProjectsResponse
	8,  // 12: project_service.ProjectService.DeleteUserProject:output_type -> project_service.DeleteUserProjectResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_src_protos_project_service_proto_init() }
func file_src_protos_project_service_proto_init() {
	if File_src_protos_project_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_project_service_proto_rawDesc), len(file_src_protos_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_project_service_proto_goTypes,
		DependencyIndexes: file_src_protos_project_service_proto_depIdxs,
		MessageInfos:      file_src_protos_project_service_proto_msgTypes,
	}.Build()
	File_src_protos_project_service_proto = out.File
	file_src_protos_project_service_proto_goTypes = nil
	file_src_protos_project_service_proto_depIdxs = nil
}
