// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: src/protos/deploy_service.proto

package deploy_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_src_protos_deploy_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_deploy_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_src_protos_deploy_service_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *Deployment) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentsRequest) Reset() {
	*x = GetDeploymentsRequest{}
	mi := &file_src_protos_deploy_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentsRequest) ProtoMessage() {}

func (x *GetDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_deploy_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_deploy_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeploymentsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentsResponse) Reset() {
	*x = GetDeploymentsResponse{}
	mi := &file_src_protos_deploy_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentsResponse) ProtoMessage() {}

func (x *GetDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_deploy_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_deploy_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_src_protos_deploy_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_deploy_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_deploy_service_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_src_protos_deploy_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_deploy_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_deploy_service_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_protos_deploy_service_proto protoreflect.FileDescriptor

const file_src_protos_deploy_service_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/protos/deploy_service.proto\x12\x0edeploy_service\"\x85\x01\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\".\n" +
	"\x15GetDeploymentsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"V\n" +
	"\x16GetDeploymentsResponse\x12<\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1a.deploy_service.DeploymentR\vdeployments\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x01\n" +
	"\rDeployService\x12_\n" +
	"\x0eGetDeployments\x12%.deploy_service.GetDeploymentsRequest\x1a&.deploy_service.GetDeploymentsResponse\x12G\n" +
	"\x06Health\x12\x1d.deploy_service.HealthRequest\x1a\x1e.deploy_service.HealthResponseB+Z)proto/deploy_service_pb;deploy_service_pbb\x06proto3"

var (
	file_src_protos_deploy_service_proto_rawDescOnce sync.Once
	file_src_protos_deploy_service_proto_rawDescData []byte
)

func file_src_protos_deploy_service_proto_rawDescGZIP() []byte {
	file_src_protos_deploy_service_proto_rawDescOnce.Do(func() {
		file_src_protos_deploy_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_deploy_service_proto_rawDesc), len(file_src_protos_deploy_service_proto_rawDesc)))
	})
	return file_src_protos_deploy_service_proto_rawDescData
}

var file_src_protos_deploy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_protos_deploy_service_proto_goTypes = []any{
	(*Deployment)(nil),             // 0: deploy_service.Deployment
	(*GetDeploymentsRequest)(nil),  // 1: deploy_service.GetDeploymentsRequest
	(*GetDeploymentsResponse)(nil), // 2: deploy_service.GetDeploymentsResponse
	(*HealthRequest)(nil),          // 3: deploy_service.HealthRequest
	(*HealthResponse)(nil),         // 4: deploy_service.HealthResponse
}
var file_src_protos_deploy_service_proto_depIdxs = []int32{
	0, // 0: deploy_service.GetDeploymentsResponse.deployments:type_name -> deploy_service.Deployment
	1, // 1: deploy_service.DeployService.GetDeployments:input_type -> deploy_service.GetDeploymentsRequest
	3, // 2: deploy_service.DeployService.Health:input_type -> deploy_service.HealthRequest
	2, // 3: deploy_service.DeployService.GetDeployments:output_type -> deploy_service.GetDeploymentsResponse
	4, // 4: deploy_service.DeployService.Health:output_type -> deploy_service.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_protos_deploy_service_proto_init() }
func file_src_protos_deploy_service_proto_init() {
	if File_src_protos_deploy_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_deploy_service_proto_rawDesc), len(file_src_protos_deploy_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_deploy_service_proto_goTypes,
		DependencyIndexes: file_src_protos_deploy_service_proto_depIdxs,
		MessageInfos:      file_src_protos_deploy_service_proto_msgTypes,
	}.Build()
	File_src_protos_deploy_service_proto = out.File
	file_src_protos_deploy_service_proto_goTypes = nil
	file_src_protos_deploy_service_proto_depIdxs = nil
}
