// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/build_service.proto

package build_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CommitHash    string                 `protobuf:"bytes,5,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_protos_build_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_protos_build_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_protos_build_service_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Build) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Build) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Build) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Build) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildsRequest) Reset() {
	*x = GetBuildsRequest{}
	mi := &file_protos_build_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildsRequest) ProtoMessage() {}

func (x *GetBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_build_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildsRequest.ProtoReflect.Descriptor instead.
func (*GetBuildsRequest) Descriptor() ([]byte, []int) {
	return file_protos_build_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBuildsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*Build               `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildsResponse) Reset() {
	*x = GetBuildsResponse{}
	mi := &file_protos_build_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildsResponse) ProtoMessage() {}

func (x *GetBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_build_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildsResponse.ProtoReflect.Descriptor instead.
func (*GetBuildsResponse) Descriptor() ([]byte, []int) {
	return file_protos_build_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuildsResponse) GetBuilds() []*Build {
	if x != nil {
		return x.Builds
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_protos_build_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_build_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_build_service_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_protos_build_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_build_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_protos_build_service_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_build_service_proto protoreflect.FileDescriptor

const file_protos_build_service_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/build_service.proto\x12\rbuild_service\"\xa3\x01\n" +
	"\x05Build\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcommit_hash\x18\x05 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\")\n" +
	"\x10GetBuildsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"A\n" +
	"\x11GetBuildsResponse\x12,\n" +
	"\x06builds\x18\x01 \x03(\v2\x14.build_service.BuildR\x06builds\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa5\x01\n" +
	"\fBuildService\x12N\n" +
	"\tGetBuilds\x12\x1f.build_service.GetBuildsRequest\x1a .build_service.GetBuildsResponse\x12E\n" +
	"\x06Health\x12\x1c.build_service.HealthRequest\x1a\x1d.build_service.HealthResponseB)Z'proto/build_service_pb;build_service_pbb\x06proto3"

var (
	file_protos_build_service_proto_rawDescOnce sync.Once
	file_protos_build_service_proto_rawDescData []byte
)

func file_protos_build_service_proto_rawDescGZIP() []byte {
	file_protos_build_service_proto_rawDescOnce.Do(func() {
		file_protos_build_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_build_service_proto_rawDesc), len(file_protos_build_service_proto_rawDesc)))
	})
	return file_protos_build_service_proto_rawDescData
}

var file_protos_build_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_build_service_proto_goTypes = []any{
	(*Build)(nil),             // 0: build_service.Build
	(*GetBuildsRequest)(nil),  // 1: build_service.GetBuildsRequest
	(*GetBuildsResponse)(nil), // 2: build_service.GetBuildsResponse
	(*HealthRequest)(nil),     // 3: build_service.HealthRequest
	(*HealthResponse)(nil),    // 4: build_service.HealthResponse
}
var file_protos_build_service_proto_depIdxs = []int32{
	0, // 0: build_service.GetBuildsResponse.builds:type_name -> build_service.Build
	1, // 1: build_service.BuildService.GetBuilds:input_type -> build_service.GetBuildsRequest
	3, // 2: build_service.BuildService.Health:input_type -> build_service.HealthRequest
	2, // 3: build_service.BuildService.GetBuilds:output_type -> build_service.GetBuildsResponse
	4, // 4: build_service.BuildService.Health:output_type -> build_service.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_build_service_proto_init() }
func file_protos_build_service_proto_init() {
	if File_protos_build_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_build_service_proto_rawDesc), len(file_protos_build_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_build_service_proto_goTypes,
		DependencyIndexes: file_protos_build_service_proto_depIdxs,
		MessageInfos:      file_protos_build_service_proto_msgTypes,
	}.Build()
	File_protos_build_service_proto = out.File
	file_protos_build_service_proto_goTypes = nil
	file_protos_build_service_proto_depIdxs = nil
}
