apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "watch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-creator
    namespace: default
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.buildservice.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.buildservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.buildservice.name }}
    spec:
      serviceAccountName: job-creator
      containers:
        - name: {{ .Values.buildservice.name }}-container
          resources:
          {{- toYaml .Values.buildservice.resources | nindent 10 }}
          imagePullPolicy: Always
          image: {{ .Values.images.repository }}/{{ .Values.buildservice.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          envFrom:
            - secretRef:
                name: global-secret
            - secretRef:
                name: {{.Values.buildservice.name}}-secret
          ports:
            - containerPort: 8080
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.buildservice.name}}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: {{.Values.buildservice.name}}
  ports:
    - port: 8080
      targetPort: 8080
      name: grpc-server
    - port: 8081  # TODO: This port is used to allow the builder job to download source code, instead use MiniO for better storage
      targetPort: 8081
      name: http-server
