apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:
      [
        "create",
        "get",
        "list",
        "watch",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      [
        "create",
        "get",
        "list",
        "watch",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      [
        "create",
        "get",
        "list",
        "watch",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-role-binding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployservice.name}}-deployment
spec:
  selector:
    matchLabels:
      app: {{.Values.deployservice.name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployservice.name}}
    spec:
      serviceAccountName: deployer
      containers:
        - name: {{.Values.deployservice.name}}-container
          resources:
          {{- toYaml .Values.deployservice.resources | nindent 10 }}
          imagePullPolicy: Always
          image: {{ .Values.images.repository }}/{{ .Values.deployservice.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
          envFrom:
            - secretRef:
                name: global-secret
            - secretRef:
                name: {{.Values.deployservice.name}}-secret
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployservice.name}}
spec:
  selector:
    app: {{.Values.deployservice.name}}
  ports:
    - port: 8080
      targetPort: 8080
