// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: src/protos/models.proto

package models_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_PENDING   BuildStatus = 0
	BuildStatus_FAILED    BuildStatus = 1
	BuildStatus_SUCCEEDED BuildStatus = 2
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "PENDING",
		1: "FAILED",
		2: "SUCCEEDED",
	}
	BuildStatus_value = map[string]int32{
		"PENDING":   0,
		"FAILED":    1,
		"SUCCEEDED": 2,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protos_models_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_src_protos_models_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{0}
}

type DeploymentStatus int32

const (
	DeploymentStatus_DEP_PENDING   DeploymentStatus = 0
	DeploymentStatus_DEP_FAILED    DeploymentStatus = 1
	DeploymentStatus_DEP_SUCCEEDED DeploymentStatus = 2
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "DEP_PENDING",
		1: "DEP_FAILED",
		2: "DEP_SUCCEEDED",
	}
	DeploymentStatus_value = map[string]int32{
		"DEP_PENDING":   0,
		"DEP_FAILED":    1,
		"DEP_SUCCEEDED": 2,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protos_models_proto_enumTypes[1].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_src_protos_models_proto_enumTypes[1]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{1}
}

type GitProvider int32

const (
	GitProvider_GITHUB GitProvider = 0
)

// Enum value maps for GitProvider.
var (
	GitProvider_name = map[int32]string{
		0: "GITHUB",
	}
	GitProvider_value = map[string]int32{
		"GITHUB": 0,
	}
)

func (x GitProvider) Enum() *GitProvider {
	p := new(GitProvider)
	*p = x
	return p
}

func (x GitProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GitProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protos_models_proto_enumTypes[2].Descriptor()
}

func (GitProvider) Type() protoreflect.EnumType {
	return &file_src_protos_models_proto_enumTypes[2]
}

func (x GitProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GitProvider.Descriptor instead.
func (GitProvider) EnumDescriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{2}
}

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email              string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	GithubAppInstalled bool                   `protobuf:"varint,5,opt,name=github_app_installed,json=githubAppInstalled,proto3" json:"github_app_installed,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_protos_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGithubAppInstalled() bool {
	if x != nil {
		return x.GithubAppInstalled
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_src_protos_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{1}
}

func (x *UserSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserSession) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_src_protos_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DomainName    string                 `protobuf:"bytes,4,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	Runtime       string                 `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,6,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	BuildCmd      string                 `protobuf:"bytes,7,opt,name=build_cmd,json=buildCmd,proto3" json:"build_cmd,omitempty"`
	StartCmd      string                 `protobuf:"bytes,8,opt,name=start_cmd,json=startCmd,proto3" json:"start_cmd,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_src_protos_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *App) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *App) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *App) GetBuildCmd() string {
	if x != nil {
		return x.BuildCmd
	}
	return ""
}

func (x *App) GetStartCmd() string {
	if x != nil {
		return x.StartCmd
	}
	return ""
}

func (x *App) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type EnvironmentVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentVariable) Reset() {
	*x = EnvironmentVariable{}
	mi := &file_src_protos_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentVariable) ProtoMessage() {}

func (x *EnvironmentVariable) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentVariable.ProtoReflect.Descriptor instead.
func (*EnvironmentVariable) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{4}
}

func (x *EnvironmentVariable) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvironmentVariable) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EnvironmentVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvironmentVariable) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        BuildStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=models.BuildStatus" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CommitHash    string                 `protobuf:"bytes,5,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_src_protos_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{5}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Build) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_PENDING
}

func (x *Build) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Build) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Build) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Status        DeploymentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=models.DeploymentStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_src_protos_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{6}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Deployment) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *Deployment) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_DEP_PENDING
}

func (x *Deployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GitRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,3,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Provider      GitProvider            `protobuf:"varint,5,opt,name=provider,proto3,enum=models.GitProvider" json:"provider,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRepository) Reset() {
	*x = GitRepository{}
	mi := &file_src_protos_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepository) ProtoMessage() {}

func (x *GitRepository) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRepository.ProtoReflect.Descriptor instead.
func (*GitRepository) Descriptor() ([]byte, []int) {
	return file_src_protos_models_proto_rawDescGZIP(), []int{7}
}

func (x *GitRepository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitRepository) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GitRepository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *GitRepository) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GitRepository) GetProvider() GitProvider {
	if x != nil {
		return x.Provider
	}
	return GitProvider_GITHUB
}

func (x *GitRepository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_src_protos_models_proto protoreflect.FileDescriptor

const file_src_protos_models_proto_rawDesc = "" +
	"\n" +
	"\x17src/protos/models.proto\x12\x06models\"\x99\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x120\n" +
	"\x14github_app_installed\x18\x05 \x01(\bR\x12githubAppInstalled\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"x\n" +
	"\vUserSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"e\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\xf7\x01\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vdomain_name\x18\x04 \x01(\tR\n" +
	"domainName\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\x12\x19\n" +
	"\brepo_url\x18\x06 \x01(\tR\arepoUrl\x12\x1b\n" +
	"\tbuild_cmd\x18\a \x01(\tR\bbuildCmd\x12\x1b\n" +
	"\tstart_cmd\x18\b \x01(\tR\bstartCmd\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"q\n" +
	"\x13EnvironmentVariable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\xb8\x01\n" +
	"\x05Build\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.models.BuildStatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcommit_hash\x18\x05 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x9f\x01\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.models.DeploymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xc2\x01\n" +
	"\rGitRepository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tclone_url\x18\x03 \x01(\tR\bcloneUrl\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12/\n" +
	"\bprovider\x18\x05 \x01(\x0e2\x13.models.GitProviderR\bprovider\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt*5\n" +
	"\vBuildStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\r\n" +
	"\tSUCCEEDED\x10\x02*F\n" +
	"\x10DeploymentStatus\x12\x0f\n" +
	"\vDEP_PENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"DEP_FAILED\x10\x01\x12\x11\n" +
	"\rDEP_SUCCEEDED\x10\x02*\x19\n" +
	"\vGitProvider\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x00b\x06proto3"

var (
	file_src_protos_models_proto_rawDescOnce sync.Once
	file_src_protos_models_proto_rawDescData []byte
)

func file_src_protos_models_proto_rawDescGZIP() []byte {
	file_src_protos_models_proto_rawDescOnce.Do(func() {
		file_src_protos_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_models_proto_rawDesc), len(file_src_protos_models_proto_rawDesc)))
	})
	return file_src_protos_models_proto_rawDescData
}

var file_src_protos_models_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_protos_models_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_src_protos_models_proto_goTypes = []any{
	(BuildStatus)(0),            // 0: models.BuildStatus
	(DeploymentStatus)(0),       // 1: models.DeploymentStatus
	(GitProvider)(0),            // 2: models.GitProvider
	(*User)(nil),                // 3: models.User
	(*UserSession)(nil),         // 4: models.UserSession
	(*Project)(nil),             // 5: models.Project
	(*App)(nil),                 // 6: models.App
	(*EnvironmentVariable)(nil), // 7: models.EnvironmentVariable
	(*Build)(nil),               // 8: models.Build
	(*Deployment)(nil),          // 9: models.Deployment
	(*GitRepository)(nil),       // 10: models.GitRepository
}
var file_src_protos_models_proto_depIdxs = []int32{
	0, // 0: models.Build.status:type_name -> models.BuildStatus
	1, // 1: models.Deployment.status:type_name -> models.DeploymentStatus
	2, // 2: models.GitRepository.provider:type_name -> models.GitProvider
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_protos_models_proto_init() }
func file_src_protos_models_proto_init() {
	if File_src_protos_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_models_proto_rawDesc), len(file_src_protos_models_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_protos_models_proto_goTypes,
		DependencyIndexes: file_src_protos_models_proto_depIdxs,
		EnumInfos:         file_src_protos_models_proto_enumTypes,
		MessageInfos:      file_src_protos_models_proto_msgTypes,
	}.Build()
	File_src_protos_models_proto = out.File
	file_src_protos_models_proto_goTypes = nil
	file_src_protos_models_proto_depIdxs = nil
}
