// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: src/protos/user_service.proto

package user_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	GithubAppInstalled bool                   `protobuf:"varint,4,opt,name=github_app_installed,json=githubAppInstalled,proto3" json:"github_app_installed,omitempty"`
	GithubAccessToken  string                 `protobuf:"bytes,5,opt,name=github_access_token,json=githubAccessToken,proto3" json:"github_access_token,omitempty"`
	GithubRefreshToken string                 `protobuf:"bytes,6,opt,name=github_refresh_token,json=githubRefreshToken,proto3" json:"github_refresh_token,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_protos_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGithubAppInstalled() bool {
	if x != nil {
		return x.GithubAppInstalled
	}
	return false
}

func (x *User) GetGithubAccessToken() string {
	if x != nil {
		return x.GithubAccessToken
	}
	return ""
}

func (x *User) GetGithubRefreshToken() string {
	if x != nil {
		return x.GithubRefreshToken
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GithubRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,4,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	GitUrl        string                 `protobuf:"bytes,5,opt,name=git_url,json=gitUrl,proto3" json:"git_url,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,6,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Visibility    string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubRepository) Reset() {
	*x = GithubRepository{}
	mi := &file_src_protos_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepository) ProtoMessage() {}

func (x *GithubRepository) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepository.ProtoReflect.Descriptor instead.
func (*GithubRepository) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *GithubRepository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GithubRepository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GithubRepository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GithubRepository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *GithubRepository) GetGitUrl() string {
	if x != nil {
		return x.GitUrl
	}
	return ""
}

func (x *GithubRepository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *GithubRepository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GithubRepository) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_src_protos_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserSession) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   *UserSession           `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *SignInResponse) GetUserSession() *UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *SignUpResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetGithubRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGithubRepositoriesRequest) Reset() {
	*x = GetGithubRepositoriesRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubRepositoriesRequest) ProtoMessage() {}

func (x *GetGithubRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*GetGithubRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetGithubRepositoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGithubRepositoriesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GithubRepositories []*GithubRepository    `protobuf:"bytes,1,rep,name=github_repositories,json=githubRepositories,proto3" json:"github_repositories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGithubRepositoriesResponse) Reset() {
	*x = GetGithubRepositoriesResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubRepositoriesResponse) ProtoMessage() {}

func (x *GetGithubRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*GetGithubRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetGithubRepositoriesResponse) GetGithubRepositories() []*GithubRepository {
	if x != nil {
		return x.GithubRepositories
	}
	return nil
}

type ExchangeGitHubCodeForTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeGitHubCodeForTokenRequest) Reset() {
	*x = ExchangeGitHubCodeForTokenRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGitHubCodeForTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGitHubCodeForTokenRequest) ProtoMessage() {}

func (x *ExchangeGitHubCodeForTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGitHubCodeForTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeGitHubCodeForTokenRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *ExchangeGitHubCodeForTokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeGitHubCodeForTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExchangeGitHubCodeForTokenResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Scope                 string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	TokenType             string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn             int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshTokenExpiresIn int64                  `protobuf:"varint,6,opt,name=refresh_token_expires_in,json=refreshTokenExpiresIn,proto3" json:"refresh_token_expires_in,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExchangeGitHubCodeForTokenResponse) Reset() {
	*x = ExchangeGitHubCodeForTokenResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGitHubCodeForTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGitHubCodeForTokenResponse) ProtoMessage() {}

func (x *ExchangeGitHubCodeForTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGitHubCodeForTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeGitHubCodeForTokenResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExchangeGitHubCodeForTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeGitHubCodeForTokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ExchangeGitHubCodeForTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeGitHubCodeForTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeGitHubCodeForTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeGitHubCodeForTokenResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

type GetGithubUserAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGithubUserAccessTokenRequest) Reset() {
	*x = GetGithubUserAccessTokenRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubUserAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubUserAccessTokenRequest) ProtoMessage() {}

func (x *GetGithubUserAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubUserAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetGithubUserAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetGithubUserAccessTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGithubUserAccessTokenRespone struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GithubUserAccessToken string                 `protobuf:"bytes,1,opt,name=github_user_access_token,json=githubUserAccessToken,proto3" json:"github_user_access_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetGithubUserAccessTokenRespone) Reset() {
	*x = GetGithubUserAccessTokenRespone{}
	mi := &file_src_protos_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubUserAccessTokenRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubUserAccessTokenRespone) ProtoMessage() {}

func (x *GetGithubUserAccessTokenRespone) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubUserAccessTokenRespone.ProtoReflect.Descriptor instead.
func (*GetGithubUserAccessTokenRespone) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetGithubUserAccessTokenRespone) GetGithubUserAccessToken() string {
	if x != nil {
		return x.GithubUserAccessToken
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_src_protos_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{15}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_src_protos_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_src_protos_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_protos_user_service_proto protoreflect.FileDescriptor

const file_src_protos_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsrc/protos/user_service.proto\x12\fuser_service\"\xfb\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x120\n" +
	"\x14github_app_installed\x18\x04 \x01(\bR\x12githubAppInstalled\x12.\n" +
	"\x13github_access_token\x18\x05 \x01(\tR\x11githubAccessToken\x120\n" +
	"\x14github_refresh_token\x18\x06 \x01(\tR\x12githubRefreshToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xe7\x01\n" +
	"\x10GithubRepository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0edefault_branch\x18\x04 \x01(\tR\rdefaultBranch\x12\x17\n" +
	"\agit_url\x18\x05 \x01(\tR\x06gitUrl\x12\x1b\n" +
	"\tclone_url\x18\x06 \x01(\tR\bcloneUrl\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\"X\n" +
	"\vUserSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x04user\x18\x02 \x01(\v2\x12.user_service.UserR\x04user\"0\n" +
	"\vAuthRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"6\n" +
	"\fAuthResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.user_service.UserR\x04user\"A\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\x0eSignInResponse\x12<\n" +
	"\fuser_session\x18\x01 \x01(\v2\x19.user_service.UserSessionR\vuserSession\"]\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"8\n" +
	"\x0eSignUpResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.user_service.UserR\x04user\"7\n" +
	"\x1cGetGithubRepositoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"p\n" +
	"\x1dGetGithubRepositoriesResponse\x12O\n" +
	"\x13github_repositories\x18\x01 \x03(\v2\x1e.user_service.GithubRepositoryR\x12githubRepositories\"P\n" +
	"!ExchangeGitHubCodeForTokenRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xf9\x01\n" +
	"\"ExchangeGitHubCodeForTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\x127\n" +
	"\x18refresh_token_expires_in\x18\x06 \x01(\x03R\x15refreshTokenExpiresIn\":\n" +
	"\x1fGetGithubUserAccessTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x1fGetGithubUserAccessTokenRespone\x127\n" +
	"\x18github_user_access_token\x18\x01 \x01(\tR\x15githubUserAccessToken\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x88\x05\n" +
	"\vUserService\x12=\n" +
	"\x04Auth\x12\x19.user_service.AuthRequest\x1a\x1a.user_service.AuthResponse\x12C\n" +
	"\x06SignIn\x12\x1b.user_service.SignInRequest\x1a\x1c.user_service.SignInResponse\x12C\n" +
	"\x06SignUp\x12\x1b.user_service.SignUpRequest\x1a\x1c.user_service.SignUpResponse\x12p\n" +
	"\x15GetGithubRepositories\x12*.user_service.GetGithubRepositoriesRequest\x1a+.user_service.GetGithubRepositoriesResponse\x12\x7f\n" +
	"\x1aExchangeGitHubCodeForToken\x12/.user_service.ExchangeGitHubCodeForTokenRequest\x1a0.user_service.ExchangeGitHubCodeForTokenResponse\x12x\n" +
	"\x18GetGithubUserAccessToken\x12-.user_service.GetGithubUserAccessTokenRequest\x1a-.user_service.GetGithubUserAccessTokenRespone\x12C\n" +
	"\x06Health\x12\x1b.user_service.HealthRequest\x1a\x1c.user_service.HealthResponseB'Z%proto/user_service_pb;user_service_pbb\x06proto3"

var (
	file_src_protos_user_service_proto_rawDescOnce sync.Once
	file_src_protos_user_service_proto_rawDescData []byte
)

func file_src_protos_user_service_proto_rawDescGZIP() []byte {
	file_src_protos_user_service_proto_rawDescOnce.Do(func() {
		file_src_protos_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_user_service_proto_rawDesc), len(file_src_protos_user_service_proto_rawDesc)))
	})
	return file_src_protos_user_service_proto_rawDescData
}

var file_src_protos_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_src_protos_user_service_proto_goTypes = []any{
	(*User)(nil),                               // 0: user_service.User
	(*GithubRepository)(nil),                   // 1: user_service.GithubRepository
	(*UserSession)(nil),                        // 2: user_service.UserSession
	(*AuthRequest)(nil),                        // 3: user_service.AuthRequest
	(*AuthResponse)(nil),                       // 4: user_service.AuthResponse
	(*SignInRequest)(nil),                      // 5: user_service.SignInRequest
	(*SignInResponse)(nil),                     // 6: user_service.SignInResponse
	(*SignUpRequest)(nil),                      // 7: user_service.SignUpRequest
	(*SignUpResponse)(nil),                     // 8: user_service.SignUpResponse
	(*GetGithubRepositoriesRequest)(nil),       // 9: user_service.GetGithubRepositoriesRequest
	(*GetGithubRepositoriesResponse)(nil),      // 10: user_service.GetGithubRepositoriesResponse
	(*ExchangeGitHubCodeForTokenRequest)(nil),  // 11: user_service.ExchangeGitHubCodeForTokenRequest
	(*ExchangeGitHubCodeForTokenResponse)(nil), // 12: user_service.ExchangeGitHubCodeForTokenResponse
	(*GetGithubUserAccessTokenRequest)(nil),    // 13: user_service.GetGithubUserAccessTokenRequest
	(*GetGithubUserAccessTokenRespone)(nil),    // 14: user_service.GetGithubUserAccessTokenRespone
	(*HealthRequest)(nil),                      // 15: user_service.HealthRequest
	(*HealthResponse)(nil),                     // 16: user_service.HealthResponse
}
var file_src_protos_user_service_proto_depIdxs = []int32{
	0,  // 0: user_service.UserSession.user:type_name -> user_service.User
	0,  // 1: user_service.AuthResponse.user:type_name -> user_service.User
	2,  // 2: user_service.SignInResponse.user_session:type_name -> user_service.UserSession
	0,  // 3: user_service.SignUpResponse.user:type_name -> user_service.User
	1,  // 4: user_service.GetGithubRepositoriesResponse.github_repositories:type_name -> user_service.GithubRepository
	3,  // 5: user_service.UserService.Auth:input_type -> user_service.AuthRequest
	5,  // 6: user_service.UserService.SignIn:input_type -> user_service.SignInRequest
	7,  // 7: user_service.UserService.SignUp:input_type -> user_service.SignUpRequest
	9,  // 8: user_service.UserService.GetGithubRepositories:input_type -> user_service.GetGithubRepositoriesRequest
	11, // 9: user_service.UserService.ExchangeGitHubCodeForToken:input_type -> user_service.ExchangeGitHubCodeForTokenRequest
	13, // 10: user_service.UserService.GetGithubUserAccessToken:input_type -> user_service.GetGithubUserAccessTokenRequest
	15, // 11: user_service.UserService.Health:input_type -> user_service.HealthRequest
	4,  // 12: user_service.UserService.Auth:output_type -> user_service.AuthResponse
	6,  // 13: user_service.UserService.SignIn:output_type -> user_service.SignInResponse
	8,  // 14: user_service.UserService.SignUp:output_type -> user_service.SignUpResponse
	10, // 15: user_service.UserService.GetGithubRepositories:output_type -> user_service.GetGithubRepositoriesResponse
	12, // 16: user_service.UserService.ExchangeGitHubCodeForToken:output_type -> user_service.ExchangeGitHubCodeForTokenResponse
	14, // 17: user_service.UserService.GetGithubUserAccessToken:output_type -> user_service.GetGithubUserAccessTokenRespone
	16, // 18: user_service.UserService.Health:output_type -> user_service.HealthResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_src_protos_user_service_proto_init() }
func file_src_protos_user_service_proto_init() {
	if File_src_protos_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_user_service_proto_rawDesc), len(file_src_protos_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_user_service_proto_goTypes,
		DependencyIndexes: file_src_protos_user_service_proto_depIdxs,
		MessageInfos:      file_src_protos_user_service_proto_msgTypes,
	}.Build()
	File_src_protos_user_service_proto = out.File
	file_src_protos_user_service_proto_goTypes = nil
	file_src_protos_user_service_proto_depIdxs = nil
}
